<div>
<table style="width: 100%">
	<tr>
		<td>
		<table style="width: 100%">
			<tr>
                <td ><center><font size="30">WSD - Module 11</font><center>
                    <center><font size="30">Topic: Programming</font><center></td>
			</tr>
			<tr>
                <td><center><font size="5">Jupyter Notebook 4</font><center></td>
			</tr>
			<tr>
                <td><center><font size="10">Numpy Arrays<span style='background :yellow' > (self-study)</span></font><center></td>
			</tr>
		</table>
		</td>
		<td><img src='figures/ihe_logo.png' width="200" height="200"></img></td>
	</tr>
</table>
</div>    

# Table of contents
1. [Learning objectives](#learningobs)
2. [NumPy arrays](#numpy_arrays)


# 1. Learning objectives<a name="learningobs"></a>

At the end of this session you will be able to:
- Explain what a NumPy Aarray is
- Create, access and apply different methods to NumPy arrays.

# 2. NumPy arrays<a name="numpy_arrays"></a>

## 2.1. Description
`NumPy` (Numerical Python) is the fundamental package for scientific computing in Python. You may recall that we used it in our first lesson to retrieve the value of $\pi$ and to use math functions such as `sqrt()` and `sin()`. We also saw that, in order to use it, it needs to be imported first using `import numpy as `{<i>name</i>}, where {<i>name</i>} can be any string. However, we will always use `np` as {<i>name</i>}, because this is a widely adopted convention that we should follow. 

Apart from these basic math operations (and more foun at https://numpy.org/doc/stable/user/whatisnumpy.html), `NumPy` provides a multidimensional array type (`ndarray`), with methods that allow for fast operations on arrays.

## 2.2. Creating NumPy arrays
Remember to first `import numpy as np` to be able to use all NumPy functions and types.

In [ ]:
import numpy as np

The following line creates a (,3) array (a vector of three elements, or, in other words, a matrix with 1 row and 3 columns):

In [ ]:
a = np.array([1,2,3])

The following line creates a (2, 3) array (a matrix of two rows and three columns):

In [ ]:
b = np.array([[1,2,3], [1,2,3]])

### Action:

Note that when you run the cells above you do not get an output. Modify them, adding the print() function, to check the arrays.

<p style="border:3px; border-style:solid; border-color:#FF0000; padding: 1em;">A common source of confusion is the difference between <b>numpy.array</b> and <b>numpy.ndarray</b>. <br>Basically, <b>numpy.array</b> is a <i>function</i> that returns a variable of type <b>numpy.ndarray</b></p>

So, for the examples above, both `type(a)` and `type(b)` will return `numpy.ndarray`.

## 2.3. Array operations 
`ndarrays` allows for carrying out complex mathematical operations that are not straightforward with lists or tuples. For example, given arrays `a` and `b`, valid element-wise oprerations are:

    a + a
    a + b
    a * b
    a / b

Similarly, linear algebra operations can be carried out using `numpy` library functions, such as:

    np.transpose(b)  # Transpose of the matrix b (or, in a simplified form: b.T)
    np.dot(a, b.T)   # Dot product of two arrays
    

### Action
In the cell below:
- Create the lists `x=[1,2,3]` and `y=[3,4,5]` 

Summing up all the elements of the list `x` with the corresponding elements of the list `y` (pair-wise sum) using lists is, unfortunately, not so trivial. However, we can use `ndarrays`.

- Create the `ndarrays` `c` and `d` out of the lists `x` and `y` as explained in section 3.2.
- Do the same pair-wise sum between `c` and `d`
- Explore other NumPy arrays operations described above


In [ ]:
# Type here your code


<b>Notes</b>: 
- The number of dimensions of an array is known as the <i>rank</i> of the array. 
- The `shape` of an array is a `tuple` of integers representing the size of the array along each dimension.
- Arrays can have an unlimited number of dimensions.

## 2.4. Commands to create arrays 

`numpy` provides many functions to create arrays in different convenient ways:

    a = np.zeros((2,2))
    b = np.ones((1,2))
    c = np.full((2,2), 7)
    d = np.eye(2)
    e = np.random.random((2,2))

#### Action:
Try the lines of code above, one by one, in the cell below, followed by a corresponding `print` statement. Try to understand yourself the obtained outcomes. After understanding each line, add a comment in front of each line for your future reference. (use the `#` to add a comment). An example is provided for the first line.

In [ ]:
# Try your code here:
a = np.zeros((2,2))  # Creates an array of 2x2 where all elements are zeros.
print(a)

## 2.5. Array indexing

Array indexing is about using square brackets (`[]`) to refer to a position of one or more elements in the array. Let's consider the following matrix:

$$a = \begin {bmatrix}
    1 & 2 & 3 & 4\\
    5 & 6 & 7 & 8\\
    9 & 10 & 11 & 12\\
    \end{bmatrix}$$
    
    
We saw before that we can create it using the `np.array` function as follows:

    a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
    
To access elements we use indexing, in a similar way to Python lists. For example, the element with value `7`, located in the <b>second row and third column </b>of `a`, is accessed as:

    a[1,2]
    
A very common mistake is to use `a[2,3]`. Why is this wrong? Because, as in sequences, <b>the indexes start from `0`, not from `1` </b>.

Note also that the notation is always <b>[ row, column ]</b>.

In [ ]:
# Try your code here

import numpy as np
np.sqrt(2)


Note that `y=np.array([3,4,5])` will produce the row vector

    [3 4 5]

whereas `y=np.array([[3,4,5]])` will produce the column vector

The first we cannot transpose, but the second we can.

`y.T` yields:

    [[3]
     [4]
     [5]]


In [ ]:
y=np.array([[3,4,5]])
print(y.T)

## 2.6. Slicing
Slicing is a methodological way to access subsets of data, and it can be done for different data types. We will see here NumPy array slicing, which uses combinations of indexes, square brackets (`[]`), commas (`,`) and colons (`:`). In particular, <b>commas</b> are used to specify the dimension we are interested on, and <b>colons</b> to indicate the start and end of a "slide". 

Observe the following slicing expressions applied to the array `a` created above:
    
`a[:]` (equivalent to `a[:,:]`) will return:

    [[ 1  2  3  4]
     [ 5  6  7  8]
     [ 9 10 11 12]]     this is, retrieve all the elements of the array.
     
    
`a[1:]` (equivalent to `a[1:,:]`), will return:

    [[ 5  6  7  8]
     [ 9 10 11 12]]     this is, starting in row with index 1 (the second one), retrieve all the columns.
     
     
However, `a[1]`, (which is equivalent to `a[1,:]`) will return:

    [5 6 7 8]           this is, retrieve all the columns of the row with index 1 (the second row).
    
    

and `a[:,1]` will return

    [ 2  6 10]          this is, retrieve all the rows of the column with index 1 (the second column).
    

Note that `a[-1]`, (which is equivalent to `a[-1,:]`) will return:

    [ 9 10 11 12]       this is, retrieve all columns of the last row.
    

Similarly, `a[:,-1]` will return
    
    [4  8 12]           this is, retrieve all the rows of the last column.
    

Also, `a[:-1]` (which is equivalent to `a[:-1,:])`, will return:

    [[1 2 3 4]
     [5 6 7 8]]         this is, retrieve all columns of all rows but the last.
     
     
The expression, `a[:,1:3]`, will retrieve:

    [[ 2  3]
     [ 6  7]
     [10 11]]      retrieve all rows starting from the second column (index 1) to the third (index 3).  


The use of more than two colons suggests that some elements are skipped. For example, the expression `a[0:4:2]` (how else can it be written?) yields:

    [[ 1  2  3  4]
     [ 9 10 11 12]]   
     
     Retrieve all columns. From the first row (0), until (not including) the fourth (4) one, skip every other file (2).
     

Another example: The expression `a[:,0:4:2]` yields:

    [[ 1  3]
     [ 5  7]
     [ 9 11]]     
     
     Retrieve all rows. From the first column (0), until (not including) the fourth (4) one, skip every other column (2).
     

### Action
Using the same matrix `a` defined above, try the following line in the cell below and explain the output.

    b = a[:2, 1:3]
    

In [ ]:
# Try your code here
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

print(a.T)

b = np.array([1,2,3,4,5,6,7,8])
print(b.T)

As you see, a sliced array is like viewing the data through a reduced window of a particular shape. <b>Note: If the sliced array is modified, the original array is also modified</b>. See the example below.

### Action
Explain the outputs of the code below. Note that `b` is defined as a slice of `a` (`b= a[:2, 1:3]`); Therefore, `b` is a "window" that can <i>see</i> part of the original matrix `a`. Which part?

    a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
    b= a[:2, 1:3]
    print(b)
    b[0, 0] = 77
    print(a)

In [ ]:
#Try your code here:


Matrices and arrays will be largely used in the coming lessons. Further details on slicing can be found at https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html